import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import zlib from 'node:zlib';
import { renderHtmlToPdf, verifyRenderingQuality } from '../src/index.js';
import {
  cssNeedsUnicodeTextLayer,
  decodeWinAnsi,
  markupNeedsUnicodeTextLayer,
  needsUnicodeTextLayer,
  standardFontRuns,
  toWinAnsi,
} from '../src/core/winAnsiText.js';
import { resolvePageZoneContent } from '../src/renderers/headerFooterRenderer.js';

// Invisible characters are built from their code points so that no formatter can turn them into literals.
const NARROW_NO_BREAK_SPACE = String.fromCharCode(0x202f);
const NO_BREAK_SPACE = String.fromCharCode(0xa0);
const COMBINING_ACUTE = String.fromCharCode(0x0301);
const ZERO_WIDTH_SPACE = String.fromCharCode(0x200b);
const EMOJI_PRESENTATION = String.fromCharCode(0xfe0f);

/** Concatenated, decompressed content streams of a PDF generated by PDFKit. */
function contentStreams(pdf: Buffer): string {
  const binary = pdf.toString('binary');
  let content = '';
  for (const match of binary.matchAll(/stream\n([\s\S]*?)\nendstream/g)) {
    try {
      content += zlib.inflateSync(Buffer.from(match[1] as string, 'binary')).toString('latin1');
    } catch {
      // Not a deflate stream (fonts, images...)
    }
  }
  return content;
}

function hex(text: string): string {
  return Buffer.from(text, 'latin1').toString('hex');
}

/** Text drawn by each TJ operator, one line per operator (kerning adjustments are ignored). */
function drawnLines(pdf: Buffer): string[] {
  return [...contentStreams(pdf).matchAll(/\[([^\]]*)\]\s*TJ/g)].map(([, array]) =>
    [...(array as string).matchAll(/<([0-9a-f]*)>/g)]
      .map(([, bytes]) => decodeWinAnsi(Buffer.from(bytes as string, 'hex')))
      .join(''),
  );
}

function hasControlCharacter(text: string): boolean {
  return [...text].some((char) => (char.codePointAt(0) as number) < 0x20);
}

describe('Standard fonts: Unicode to WinAnsi mapping', () => {
  test('keeps WinAnsi text unchanged', () => {
    const text = 'Œuvre “citée” — 12 € … l’été ™';
    assert.equal(toWinAnsi(text), text);
  });

  test('maps typographic variants to their WinAnsi equivalents', () => {
    assert.equal(toWinAnsi(`1${NARROW_NO_BREAK_SPACE}655,00 €`), `1${NO_BREAK_SPACE}655,00 €`);
    assert.equal(toWinAnsi('ﬁnance'), 'finance');
    assert.equal(toWinAnsi(`e${COMBINING_ACUTE}te${COMBINING_ACUTE}`), 'été');
    assert.equal(toWinAnsi('Łódź ő ș'), 'Lódz o s');
    assert.equal(toWinAnsi('a ≤ b → c'), 'a <= b -> c');
    assert.equal(toWinAnsi(`x${ZERO_WIDTH_SPACE}y`), 'xy');
  });

  test('drops symbols without a glyph, with the space that follows them', () => {
    assert.equal(toWinAnsi('✔ Signature Électronique Certifiée'), 'Signature Électronique Certifiée');
    assert.equal(toWinAnsi('🌱 Végétarien'), 'Végétarien');
    assert.equal(toWinAnsi(`⚠${EMOJI_PRESENTATION} Attention`), 'Attention');
    assert.equal(toWinAnsi('Prix ✓ OK'), 'Prix OK');
  });

  test('draws U+202F thousands separators instead of corrupting the hex string', async () => {
    const html = `<p>Total : 1${NARROW_NO_BREAK_SPACE}655,00 € 🌱 fin</p>`;
    const lines = drawnLines(await renderHtmlToPdf(html, { gpu: false }));
    // PDFKit wrote U+202F as the four hex digits "202f", i.e. the two glyphs " /".
    assert.deepEqual(lines, [`Total : 1${NO_BREAK_SPACE}655,00 € fin`]);
  });

  test('splits symbols into Symbol and ZapfDingbats runs', () => {
    assert.equal(standardFontRuns('Texte simple'), null);
    assert.deepEqual(standardFontRuns('✔ Validé'), [
      { font: 'ZapfDingbats', text: '4', width: 846 },
      { font: 'text', text: ' Validé', width: 0 },
    ]);
    assert.deepEqual(
      standardFontRuns('β ≤ 🌱 x').map((run) => run.font),
      ['Symbol', 'text', 'Symbol', 'text'],
      'the emoji without a glyph is dropped with its space',
    );
  });

  test('detects the documents that need the Unicode text layer', () => {
    assert.equal(needsUnicodeTextLayer('Œuvre “citée” — 12 € … l’été'), false);
    assert.equal(needsUnicodeTextLayer('5 µg'), true, 'text-transform: uppercase turns µ into Greek Μ');
    assert.equal(needsUnicodeTextLayer('Validé ✔'), true);
    assert.equal(cssNeedsUnicodeTextLayer('p { color: red; content: "\\00e9"; }'), false);
    assert.equal(cssNeedsUnicodeTextLayer('@page { @top-left { content: "\\2714  Validé"; } }'), true);
    assert.equal(markupNeedsUnicodeTextLayer('<b>Page {page}</b>'), false);
    assert.equal(markupNeedsUnicodeTextLayer('<b>&#x2714; Validé</b>'), true);
  });

  test('draws symbols written as character references or CSS escapes', async () => {
    const pdf = await renderHtmlToPdf(
      '<style>@page { @top-left { content: "\\2605  Zone"; } }</style><p>&#x2714; Validé</p>',
      { gpu: false },
    );
    const lines = drawnLines(pdf);
    assert.ok(lines.includes('4'), 'the ✔ reference is drawn with ZapfDingbats');
    assert.ok(lines.includes('H'), 'the ★ escape of the @page zone is drawn with ZapfDingbats');
  });

  test('draws symbols with the standard symbol fonts in their built-in encoding', async () => {
    const pdf = await renderHtmlToPdf('<p style="text-align: right">Prix ≤ 5 € ✔</p>', { gpu: false });
    const fonts = [...pdf.toString('latin1').matchAll(/<<[^>]*\/BaseFont \/(\w+)[^>]*>>/g)];
    const encodingOf = (name: string) => fonts.find((match) => match[1] === name)?.[0].includes('/Encoding');
    assert.equal(encodingOf('Helvetica'), true);
    assert.equal(encodingOf('Symbol'), false, 'symbolic fonts keep their built-in encoding');
    assert.equal(encodingOf('ZapfDingbats'), false);
    assert.deepEqual(drawnLines(pdf), ['Prix ', '£', ' 5 € ', '4']);
  });
});

describe('Quality auditor: PDF text extraction', () => {
  test('reads justified text: word gaps are TJ adjustments, typographic quotes are WinAnsi bytes', async () => {
    const paragraph =
      'Les Parties envisagent des pourparlers stratégiques en vue d’une coopération industrielle et ' +
      'technologique relative au déploiement conjoint d’architectures logicielles distribuées. Chacune des ' +
      'Parties sera nécessairement amenée à divulguer à l’autre des informations techniques et commerciales.';
    const html = `<p style="text-align: justify; font-size: 10px">${paragraph}</p>`;
    const pdf = await renderHtmlToPdf(html, { gpu: false });
    assert.match(contentStreams(pdf), /> -\d+(?:\.\d+)? </, 'the paragraph should be justified with TJ offsets');

    const audit = await verifyRenderingQuality(html, pdf);
    assert.equal(audit.textCompleteness.rate, 1);
    assert.ok(audit.textCompleteness.sequenceAlignmentRate >= 0.95);
  });

  test('decompresses a content stream whose compressed data ends with a line feed byte', async () => {
    const words = 'Hello fidelity audit';
    let deflated = Buffer.alloc(0);
    // The last byte is the low byte of the Adler-32 byte sum: n × "a" (0x61, odd) reaches every residue.
    for (let n = 0; n < 512 && deflated.at(-1) !== 0x0a; n++) {
      deflated = zlib.deflateSync(`BT /F1 12 Tf 1 0 0 1 72 720 Tm [<${hex(words)}>] TJ ET\n%${'a'.repeat(n)}`);
    }
    assert.equal(deflated.at(-1), 0x0a, 'no sample with an Adler-32 checksum ending in 0x0A');

    const pdf = Buffer.concat([
      Buffer.from(`%PDF-1.3\n1 0 obj\n<< /Type /Page >>\nendobj\n2 0 obj\n<< /Length ${deflated.length} >>\nstream\n`),
      deflated,
      Buffer.from('\nendstream\nendobj\n%%EOF\n'),
    ]);
    const audit = await verifyRenderingQuality(`<p>${words}</p>`, pdf);
    assert.equal(audit.textCompleteness.rate, 1);
  });
});

describe('Inline boxes (badges)', () => {
  test('wrap onto a new line within their container, separated by white space and margins', async () => {
    const badges = Array.from({ length: 12 }, (_, i) => `<span class="b">Badge ${i}</span>`).join(' ');
    const html = `<style>.b { display: inline-block; background-color: #eee; padding: 2px 6px; margin: 0 4px 4px 0; }</style>
      <div style="width: 50%">${badges}</div>`;
    const content = contentStreams(await renderHtmlToPdf(html, { gpu: false, margin: { left: 20, right: 20 } }));
    const positions = [...content.matchAll(/1 0 0 1 ([\d.]+) ([\d.]+) Tm/g)].map(([, x, y]) => [Number(x), Number(y)]);
    assert.equal(positions.length, 12);
    assert.ok(new Set(positions.map(([, y]) => y)).size >= 2, 'the badges wrap onto several lines');
    assert.ok(
      positions.every(([x]) => (x as number) < 595.28 - 20),
      'no badge starts beyond the right margin',
    );
  });
});

describe('CSS paged media and inheritance', () => {
  test('resolves @page margin box content strings, escapes and counters', () => {
    assert.equal(
      resolvePageZoneContent({ content: '"Page " counter(page) " sur " counter(num-pages)' }, 2, 5),
      'Page 2 sur 5',
    );
    assert.equal(
      resolvePageZoneContent({ content: `"LABORATOIRE D'ANALYSES \\2014  BIOSANTÉ"` }, 1, 1),
      "LABORATOIRE D'ANALYSES — BIOSANTÉ",
    );
    assert.equal(resolvePageZoneContent({ content: "'L\\'équipe'" }, 1, 1), "L'équipe");
    assert.equal(resolvePageZoneContent({ content: 'none' }, 1, 1), '');
  });

  test('inherits the body font size (9px = 6.75pt) in paragraphs and table cells', async () => {
    const html = `<html><head><style>body { font-size: 9px; }</style></head>
      <body><p>Paragraph</p><div>Division</div><table><tr><td>Cell</td></tr></table></body></html>`;
    const content = contentStreams(await renderHtmlToPdf(html, { gpu: false }));
    const sizes = new Set([...content.matchAll(/\/F\d+ ([\d.]+) Tf/g)].map((match) => match[1]));
    assert.deepEqual([...sizes], ['6.75']);
  });

  test('renders the medical report demo without zone overlap nor garbled symbols', async () => {
    const html = readFileSync(new URL('../demo/templates/7-medical-report.html', import.meta.url), 'utf8');
    const options = { format: 'A4', margin: { top: 18, bottom: 18, left: 22, right: 22 }, gpu: false } as const;
    const pdf = await renderHtmlToPdf(html, options);
    const audit = await verifyRenderingQuality(html, pdf, { options: options as never });

    assert.equal(audit.layout.collisionsCount, 0);
    assert.ok(audit.score >= 95, `fidelity ${audit.score}% (${audit.grade})`);
    const lines = drawnLines(pdf);
    // ✔ is drawn with ZapfDingbats (byte "4"), instead of the stray "'" PDFKit used to write.
    const signature = lines.indexOf(' Signature Électronique Certifiée');
    assert.equal(lines[signature - 1], '4');
    assert.ok(!lines.some(hasControlCharacter));
  });
});
