/**
 * src/core/pdfkitAccelerator.ts
 *
 * Byte-exact acceleration layer for PDFKit 0.20.x internals.
 *
 * Profiling shows that most of the rendering time is not spent in this module's layout code but in
 * PDFKit's standard-font (AFM) machinery, which works on glyph *names*:
 *  - every document re-decodes each standard font's ~1 200 kerning pairs into string-keyed objects
 *    (~65% of `new PDFDocument()`),
 *  - every measured or rendered character costs a string concatenation plus several dictionary-mode
 *    property lookups (`getKernPair`, `widthOfGlyph`, `characterToGlyph`),
 *  - every content-stream operator is copied into its own `Uint8Array` before being re-concatenated,
 *  - every `fillColor('#rrggbb')` re-parses the hex string and re-formats three floats.
 *
 * This module replaces those hot paths with equivalent implementations:
 *  1. Font metrics flyweight: AFM metrics are decoded once per process and shared by every document.
 *  2. Compiled metrics: widths and kerning are compiled into typed arrays indexed by char code, and
 *     glyph position records are interned (frozen, shared), so encoding a line allocates two arrays
 *     instead of five objects per glyph.
 *  3. Color operator cache for hex/named colors (document-independent by construction).
 *  4. Content-stream coalescing: string operators are buffered and encoded once per stream.
 *
 * Safety model: each replacement is installed only if the source fingerprint of the PDFKit code it
 * replaces matches the audited 0.20.x implementation, and compiled font tables are cross-checked
 * against the original methods before use. Any mismatch silently keeps the original PDFKit code, so
 * the generated bytes are identical in every case. Set `PDF_LITE_ACCEL=off` to disable the layer.
 */

// PDFKit keeps its document state in underscore-prefixed fields (`_font`, `_fontFamilies`, ...).
/* oxlint-disable eslint/no-underscore-dangle */

import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import PDFDocument from 'pdfkit';

export interface PdfKitAcceleratorStatus {
  /** True when at least one acceleration is active. */
  readonly enabled: boolean;
  /** Shared font metrics flyweight and compiled AFM tables. */
  readonly fontMetrics: boolean;
  /** Color operator cache. */
  readonly colorCache: boolean;
  /** Single-pass content-stream encoding. */
  readonly streamCoalescing: boolean;
  /** Why an acceleration was skipped, when relevant. */
  readonly reason?: string;
}

/** Source fingerprints of the audited PDFKit 0.20.x implementations (whitespace-insensitive SHA-256). */
const KNOWN_FINGERPRINTS = {
  AFMFont: 'ce572916f66e3b01',
  StandardFont: '5abb6aca10effab4',
  PDFReference: '5866725787ce80ec',
  font: '0f6a1d8ea8791c8a',
  setColorCore: '7c39446cae7ede45',
  normalizeColor: '30c35a6eb9b6b3cd',
} as const;

/** PDFKit standard font names mapped to their `pdfkit/standard-fonts/*` data modules. */
const STANDARD_FONT_MODULES: Readonly<Record<string, string>> = {
  Courier: 'Courier',
  'Courier-Bold': 'CourierBold',
  'Courier-BoldOblique': 'CourierBoldOblique',
  'Courier-Oblique': 'CourierOblique',
  Helvetica: 'Helvetica',
  'Helvetica-Bold': 'HelveticaBold',
  'Helvetica-BoldOblique': 'HelveticaBoldOblique',
  'Helvetica-Oblique': 'HelveticaOblique',
  Symbol: 'Symbol',
  'Times-Bold': 'TimesBold',
  'Times-BoldItalic': 'TimesBoldItalic',
  'Times-Italic': 'TimesItalic',
  'Times-Roman': 'TimesRoman',
  ZapfDingbats: 'ZapfDingbats',
};

/** Upper bound for lazily memoized code units above 0xFF and for cached color strings. */
const MAX_LAZY_ENTRIES = 4096;
const MAX_COLOR_ENTRIES = 1024;

interface GlyphPosition {
  readonly xAdvance: number;
  readonly yAdvance: number;
  readonly xOffset: number;
  readonly yOffset: number;
  readonly advanceWidth: number;
}

interface AfmFontInternals {
  readonly name: string;
  readonly glyphWidths: Record<string, number>;
  readonly kernPairs: Record<string, number>;
  characterToGlyph(code: number): string;
  widthOfGlyph(glyph: string): number;
  encodeText(text: string): string[];
}

interface StandardFontInternals {
  readonly name: string;
  font: AfmFontInternals;
  encode(text: unknown): [string[], GlyphPosition[]];
  widthOfString(text: unknown, size: number): number;
}

interface StandardFontData {
  glyphNames: string;
  glyphWidths: readonly number[];
  kernPairs: readonly unknown[];
}

interface DocumentInternals {
  _font: StandardFontInternals | null;
  _fontFamilies: Record<string, unknown>;
  _registeredFonts: Record<string, { src: unknown; family: unknown } | undefined>;
  _normalizeColor(color: unknown): unknown;
  _getColorSpace(color: unknown): string;
  _setColorSpace(space: string, stroke: boolean): unknown;
  addContent(data: string): unknown;
}

const PENDING_CONTENT: unique symbol = Symbol('pdfLitePendingContent');

interface PdfReferenceInternals {
  buffer: Uint8Array[];
  data: { Length?: number; Filter?: string };
  compress: boolean;
  uncompressedLength: number;
  [PENDING_CONTENT]?: string[];
}

type AnyFunction = (this: unknown, ...args: unknown[]) => unknown;

function fingerprint(fn: unknown): string {
  return createHash('sha256').update(String(fn).replace(/\s+/g, '')).digest('hex').slice(0, 16);
}

// ─── 1 & 2. Font metrics flyweight + compiled AFM tables ───

interface CompiledMetrics {
  readonly afm: AfmFontInternals;
  readonly glyphIndex: Map<string, number>;
  /** Glyph index for code units 0x00–0xFF. */
  readonly lowGlyph: Uint8Array;
  /** Hex encoding (as produced by `encodeText`) for code units 0x00–0xFF. */
  readonly lowHex: readonly string[];
  /** Lazily memoized glyph index / hex for code units above 0xFF. */
  readonly highGlyph: Map<number, number>;
  readonly highHex: Map<number, string>;
  /** Advance width per glyph index, in font units. */
  readonly widths: Float64Array;
  /** Compact kerning matrix: row/column per glyph index (-1 when the glyph never kerns). */
  readonly kernRow: Int16Array;
  readonly kernCol: Int16Array;
  readonly kernCols: number;
  readonly kern: Int16Array;
  /** Interned position records for unkerned glyphs, and for (glyph, kerning) pairs. */
  readonly plainPositions: readonly GlyphPosition[];
  readonly kernedPositions: Map<number, GlyphPosition>;
}

const compiledMetrics = new WeakMap<AfmFontInternals, CompiledMetrics | null>();

function compileMetrics(afm: AfmFontInternals): CompiledMetrics | null {
  const glyphIndex = new Map<string, number>();
  const names: string[] = [];
  const lowGlyph = new Uint8Array(256);
  let all256 = '';
  for (let code = 0; code < 256; code++) {
    const name = afm.characterToGlyph(code);
    let index = glyphIndex.get(name);
    if (index === undefined) {
      index = names.length;
      if (index > 255) return null;
      glyphIndex.set(name, index);
      names.push(name);
    }
    lowGlyph[code] = index;
    all256 += String.fromCharCode(code);
  }

  const lowHex = afm.encodeText(all256);
  if (lowHex.length !== 256) return null;

  const glyphCount = names.length;
  const widths = new Float64Array(glyphCount);
  for (let g = 0; g < glyphCount; g++) {
    widths[g] = afm.widthOfGlyph(names[g] as string);
  }

  // Kerning: keep only pairs reachable from WinAnsi text, packed into a dense rows × cols matrix.
  const kernRow = new Int16Array(glyphCount).fill(-1);
  const kernCol = new Int16Array(glyphCount).fill(-1);
  const pairs: number[] = [];
  let rows = 0;
  let cols = 0;
  for (const key of Object.keys(afm.kernPairs)) {
    const sep = key.indexOf('\0');
    if (sep === -1) continue;
    const rightName = key.slice(sep + 1);
    // `getKernPair(last, undefined)` looks up "<last>\0undefined": such a key would change the
    // advance of every final glyph, which the compiled tables do not model.
    if (rightName === 'undefined') return null;
    const left = glyphIndex.get(key.slice(0, sep));
    const right = glyphIndex.get(rightName);
    if (left === undefined || right === undefined) continue;
    const amount = afm.kernPairs[key] || 0;
    if (!Number.isInteger(amount) || amount < -32768 || amount > 32767) return null;
    if (kernRow[left] === -1) kernRow[left] = rows++;
    if (kernCol[right] === -1) kernCol[right] = cols++;
    pairs.push(left, right, amount);
  }
  const kern = new Int16Array(Math.max(1, rows * cols));
  for (let i = 0; i < pairs.length; i += 3) {
    kern[(kernRow[pairs[i] as number] as number) * cols + (kernCol[pairs[i + 1] as number] as number)] = pairs[
      i + 2
    ] as number;
  }

  const plainPositions: GlyphPosition[] = [];
  for (let g = 0; g < glyphCount; g++) {
    const width = widths[g] as number;
    plainPositions.push(
      Object.freeze({ xAdvance: width + 0, yAdvance: 0, xOffset: 0, yOffset: 0, advanceWidth: width }),
    );
  }

  return {
    afm,
    glyphIndex,
    lowGlyph,
    lowHex,
    highGlyph: new Map(),
    highHex: new Map(),
    widths,
    kernRow,
    kernCol,
    kernCols: cols,
    kern,
    plainPositions,
    kernedPositions: new Map(),
  };
}

function glyphOf(m: CompiledMetrics, code: number): number {
  if (code < 256) return m.lowGlyph[code] as number;
  let glyph = m.highGlyph.get(code);
  if (glyph === undefined) {
    glyph = m.glyphIndex.get(m.afm.characterToGlyph(code)) ?? -1;
    if (m.highGlyph.size < MAX_LAZY_ENTRIES) m.highGlyph.set(code, glyph);
  }
  return glyph;
}

function hexOf(m: CompiledMetrics, code: number): string {
  if (code < 256) return m.lowHex[code] as string;
  let hex = m.highHex.get(code);
  if (hex === undefined) {
    hex = m.afm.encodeText(String.fromCharCode(code))[0] as string;
    if (m.highHex.size < MAX_LAZY_ENTRIES) m.highHex.set(code, hex);
  }
  return hex;
}

function kernOf(m: CompiledMetrics, left: number, right: number): number {
  const row = m.kernRow[left] as number;
  if (row < 0) return 0;
  const col = m.kernCol[right] as number;
  return col < 0 ? 0 : (m.kern[row * m.kernCols + col] as number);
}

function kernedPosition(m: CompiledMetrics, glyph: number, amount: number): GlyphPosition {
  const key = glyph * 65536 + (amount + 32768);
  let position = m.kernedPositions.get(key);
  if (position === undefined) {
    const width = m.widths[glyph] as number;
    position = Object.freeze({ xAdvance: width + amount, yAdvance: 0, xOffset: 0, yOffset: 0, advanceWidth: width });
    m.kernedPositions.set(key, position);
  }
  return position;
}

/**
 * Sum of glyph advances (font units), accumulated in the same order and with the same operations as
 * `StandardFont#widthOfString`. Returns NaN when a code unit cannot be resolved (caller falls back).
 */
function rawWidth(m: CompiledMetrics, text: string): number {
  const length = text.length;
  if (length === 0) return 0;
  let width = 0;
  let glyph = glyphOf(m, text.charCodeAt(0));
  if (glyph < 0) return Number.NaN;
  for (let i = 1; i < length; i++) {
    const next = glyphOf(m, text.charCodeAt(i));
    if (next < 0) return Number.NaN;
    width += (m.widths[glyph] as number) + kernOf(m, glyph, next);
    glyph = next;
  }
  width += (m.widths[glyph] as number) + 0;
  return width;
}

function fastEncode(m: CompiledMetrics, text: string): [string[], GlyphPosition[]] | null {
  const encoded: string[] = [];
  const positions: GlyphPosition[] = [];
  const length = text.length;
  if (length === 0) return [encoded, positions];
  let code = text.charCodeAt(0);
  let glyph = glyphOf(m, code);
  if (glyph < 0) return null;
  for (let i = 0; i < length; i++) {
    encoded.push(hexOf(m, code));
    let amount = 0;
    let nextCode = 0;
    let nextGlyph = -1;
    if (i + 1 < length) {
      nextCode = text.charCodeAt(i + 1);
      nextGlyph = glyphOf(m, nextCode);
      if (nextGlyph < 0) return null;
      amount = kernOf(m, glyph, nextGlyph);
    }
    positions.push(amount === 0 ? (m.plainPositions[glyph] as GlyphPosition) : kernedPosition(m, glyph, amount));
    code = nextCode;
    glyph = nextGlyph;
  }
  return [encoded, positions];
}

/** Probe covering every WinAnsi code, common typographic code units and kerned pairs. */
function buildSelfTestProbe(): string {
  let probe = '';
  for (let code = 0; code < 256; code++) probe += String.fromCharCode(code);
  return `${probe}’“”–—€…Œœ™→￿ AVAWAYATLTLVLYFAPAToTaTyWaWeYoV,Y.r.y.f"L'`;
}

function samePosition(a: GlyphPosition | undefined, b: GlyphPosition | undefined): boolean {
  return (
    a !== undefined &&
    b !== undefined &&
    Object.is(a.xAdvance, b.xAdvance) &&
    Object.is(a.yAdvance, b.yAdvance) &&
    Object.is(a.xOffset, b.xOffset) &&
    Object.is(a.yOffset, b.yOffset) &&
    Object.is(a.advanceWidth, b.advanceWidth)
  );
}

function installFontMetrics(
  docProto: Record<string, unknown>,
  standardFontProto: Record<string, unknown>,
  afmProto: object,
  probeFont: StandardFontInternals,
): boolean {
  const originalFont = docProto['font'] as AnyFunction;
  const originalEncode = standardFontProto['encode'] as StandardFontInternals['encode'];
  const originalWidthOfString = standardFontProto['widthOfString'] as StandardFontInternals['widthOfString'];
  const selfTestProbe = buildSelfTestProbe();
  const require = createRequire(import.meta.url);

  const metricsFor = (font: StandardFontInternals): CompiledMetrics | null => {
    const afm = font.font;
    let metrics = compiledMetrics.get(afm);
    if (metrics !== undefined) return metrics;
    metrics = compileMetrics(afm);
    if (metrics !== null) {
      // Cross-check the compiled tables against PDFKit's own implementation before trusting them.
      const expectedWidth = originalWidthOfString.call(font, selfTestProbe, 13.5);
      const [expectedHex, expectedPositions] = originalEncode.call(font, selfTestProbe);
      const encoded = fastEncode(metrics, selfTestProbe);
      let valid =
        encoded !== null &&
        encoded[0].length === expectedHex.length &&
        Object.is(expectedWidth, rawWidth(metrics, selfTestProbe) * (13.5 / 1000));
      if (valid && encoded !== null) {
        const [hex, positions] = encoded;
        for (let i = 0; valid && i < expectedHex.length; i++) {
          valid = expectedHex[i] === hex[i] && samePosition(expectedPositions[i], positions[i]);
        }
      }
      if (!valid) metrics = null;
    }
    compiledMetrics.set(afm, metrics);
    return metrics;
  };

  standardFontProto['widthOfString'] = function widthOfString(
    this: StandardFontInternals,
    string: unknown,
    size: number,
  ): number {
    const metrics = metricsFor(this);
    if (metrics !== null) {
      const width = rawWidth(metrics, typeof string === 'string' ? string : `${string}`);
      if (width === width) {
        const scale = size / 1000;
        return width * scale;
      }
    }
    return originalWidthOfString.call(this, string, size);
  };

  standardFontProto['encode'] = function encode(
    this: StandardFontInternals,
    text: unknown,
  ): [string[], GlyphPosition[]] {
    if (typeof text === 'string') {
      const metrics = metricsFor(this);
      const result = metrics !== null ? fastEncode(metrics, text) : null;
      if (result !== null) return result;
    }
    return originalEncode.call(this, text);
  };

  // Flyweight: decode each standard font's AFM metrics once per process instead of once per document.
  const sharedAfm = new Map<string, AfmFontInternals>([[probeFont.name, probeFont.font]]);
  const fontData = new Map<string, StandardFontData | null>();
  const emptyList: readonly never[] = Object.freeze([]);

  const loadFontData = (name: string): StandardFontData | null => {
    let data = fontData.get(name);
    if (data === undefined) {
      try {
        const loaded = require(`pdfkit/standard-fonts/${STANDARD_FONT_MODULES[name]}`) as StandardFontData;
        data =
          typeof loaded?.glyphNames === 'string' && Array.isArray(loaded.glyphWidths) && Array.isArray(loaded.kernPairs)
            ? loaded
            : null;
      } catch {
        data = null;
      }
      fontData.set(name, data);
    }
    return data;
  };

  const isStandardFontObject = (font: unknown, name: string): font is StandardFontInternals =>
    font !== null &&
    typeof font === 'object' &&
    Object.getPrototypeOf(font) === standardFontProto &&
    (font as StandardFontInternals).name === name &&
    Object.getPrototypeOf((font as StandardFontInternals).font) === afmProto;

  docProto['font'] = function font(this: DocumentInternals, src: unknown, family?: unknown, size?: unknown): unknown {
    if (typeof src !== 'string') return originalFont.apply(this, arguments as never);
    const registered = this._registeredFonts[src];
    const standardName = registered === undefined ? src : registered.src;
    if (typeof standardName !== 'string' || !Object.hasOwn(STANDARD_FONT_MODULES, standardName)) {
      return originalFont.apply(this, arguments as never);
    }
    // Same cache key as PDFKit: an existing entry means no font object will be constructed.
    const cacheKey = registered === undefined ? (typeof family === 'number' ? null : family) || src : src;
    if (typeof cacheKey === 'string' && this._fontFamilies[cacheKey] !== undefined) {
      return originalFont.apply(this, arguments as never);
    }

    const shared = sharedAfm.get(standardName);
    const data = shared === undefined ? null : loadFontData(standardName);
    if (shared === undefined || data === null) {
      const result = originalFont.apply(this, arguments as never);
      if (shared === undefined && isStandardFontObject(this._font, standardName)) {
        sharedAfm.set(standardName, this._font.font);
      }
      return result;
    }

    // The AFMFont constructor only decodes glyph names, widths and kerning pairs from this shared data
    // object: hiding them for the duration of this synchronous call makes the throw-away per-document
    // instance nearly free, and it is swapped for the shared, fully decoded one right after.
    const { glyphNames, glyphWidths, kernPairs } = data;
    data.glyphNames = '';
    data.glyphWidths = emptyList;
    data.kernPairs = emptyList;
    let result: unknown;
    try {
      result = originalFont.call(this, src, family, size);
    } finally {
      data.glyphNames = glyphNames;
      data.glyphWidths = glyphWidths;
      data.kernPairs = kernPairs;
    }
    const current = this._font;
    if (isStandardFontObject(current, standardName) && current.font !== shared) {
      current.font = shared;
    }
    return result;
  };

  return true;
}

// ─── 3. Color operator cache ───

function installColorCache(docProto: Record<string, unknown>): boolean {
  const originalSetColorCore = docProto['_setColorCore'] as AnyFunction;
  // Hex and named colors normalize to the same array in every document (they are resolved before
  // per-document spot colors), so their operator operands can be shared process-wide.
  const colorOperands = new Map<string, { readonly space: string; readonly values: string }>();

  docProto['_setColorCore'] = function _setColorCore(
    this: DocumentInternals,
    color: unknown,
    stroke: boolean,
  ): unknown {
    if (typeof color === 'string') {
      let entry = colorOperands.get(color);
      if (entry === undefined) {
        const normalized = this._normalizeColor(color);
        if (Array.isArray(normalized)) {
          entry = { space: this._getColorSpace(normalized), values: normalized.join(' ') };
          if (colorOperands.size < MAX_COLOR_ENTRIES) colorOperands.set(color, entry);
        }
      }
      if (entry !== undefined) {
        this._setColorSpace(entry.space, stroke);
        this.addContent(`${entry.values} ${stroke ? 'SCN' : 'scn'}`);
        return true;
      }
    }
    return originalSetColorCore.apply(this, arguments as never);
  };
  return true;
}

// ─── 4. Content-stream coalescing ───

function flushPendingContent(ref: PdfReferenceInternals): void {
  const pending = ref[PENDING_CONTENT];
  if (pending !== undefined && pending.length > 0) {
    // latin1 keeps the low byte of each UTF-16 code unit, exactly like PDFKit's `fromBinaryString`.
    ref.buffer.push(Buffer.from(pending.length === 1 ? (pending[0] as string) : pending.join(''), 'latin1'));
    pending.length = 0;
  }
}

function installStreamCoalescing(referenceProto: Record<string, unknown>): boolean {
  const originalWrite = referenceProto['write'] as AnyFunction;
  const originalFinalize = referenceProto['finalize'] as AnyFunction;

  referenceProto['write'] = function write(this: PdfReferenceInternals, chunk: unknown): unknown {
    if (chunk instanceof Uint8Array) {
      flushPendingContent(this);
      return originalWrite.call(this, chunk as never);
    }
    // `+` (not a template literal) to keep PDFKit's exact coercion semantics for non-string chunks.
    const line = (chunk as string) + '\n';
    const pending = this[PENDING_CONTENT];
    if (pending === undefined) this[PENDING_CONTENT] = [line];
    else pending.push(line);
    // Same bookkeeping as PDFKit: one byte per code unit.
    this.uncompressedLength += line.length;
    if (this.data.Length == null) this.data.Length = 0;
    this.data.Length += line.length;
    if (this.compress) this.data.Filter = 'FlateDecode';
    return undefined;
  };

  referenceProto['finalize'] = function finalize(this: PdfReferenceInternals): unknown {
    flushPendingContent(this);
    return originalFinalize.call(this);
  };
  return true;
}

// ─── Installation ───

let acceleratorStatus: PdfKitAcceleratorStatus | null = null;

function disabled(reason: string): PdfKitAcceleratorStatus {
  return { enabled: false, fontMetrics: false, colorCache: false, streamCoalescing: false, reason };
}

function installAccelerator(): PdfKitAcceleratorStatus {
  if (process.env['PDF_LITE_ACCEL'] === 'off') return disabled('disabled by PDF_LITE_ACCEL=off');

  let probe: { _font?: StandardFontInternals; _root?: object };
  try {
    probe = new (PDFDocument as unknown as new (options: object) => typeof probe)({ autoFirstPage: false });
  } catch (err) {
    return disabled(`probe document failed: ${(err as Error).message}`);
  }
  const probeFont = probe._font;
  if (!probeFont?.font || !probe._root) return disabled('unrecognised PDFKit internals');

  const docProto = PDFDocument.prototype as unknown as Record<string, unknown>;
  const standardFontProto = Object.getPrototypeOf(probeFont) as Record<string, unknown>;
  const afmProto = Object.getPrototypeOf(probeFont.font) as object;
  const referenceProto = Object.getPrototypeOf(probe._root) as Record<string, unknown>;
  const skipped: string[] = [];

  const fontMetrics =
    fingerprint(afmProto.constructor) === KNOWN_FINGERPRINTS.AFMFont &&
    fingerprint(standardFontProto['constructor']) === KNOWN_FINGERPRINTS.StandardFont &&
    fingerprint(docProto['font']) === KNOWN_FINGERPRINTS.font &&
    installFontMetrics(docProto, standardFontProto, afmProto, probeFont);
  if (!fontMetrics) skipped.push('fontMetrics');

  const colorCache =
    fingerprint(docProto['_setColorCore']) === KNOWN_FINGERPRINTS.setColorCore &&
    fingerprint(docProto['_normalizeColor']) === KNOWN_FINGERPRINTS.normalizeColor &&
    installColorCache(docProto);
  if (!colorCache) skipped.push('colorCache');

  const streamCoalescing =
    fingerprint(referenceProto['constructor']) === KNOWN_FINGERPRINTS.PDFReference &&
    installStreamCoalescing(referenceProto);
  if (!streamCoalescing) skipped.push('streamCoalescing');

  return {
    enabled: fontMetrics || colorCache || streamCoalescing,
    fontMetrics,
    colorCache,
    streamCoalescing,
    ...(skipped.length > 0 ? { reason: `unrecognised PDFKit implementation for: ${skipped.join(', ')}` } : {}),
  };
}

/**
 * Installs the acceleration layer once per process (or worker thread) and returns its status.
 * Subsequent calls are free.
 */
export function ensurePdfKitAccelerator(): PdfKitAcceleratorStatus {
  if (acceleratorStatus === null) {
    acceleratorStatus = installAccelerator();
  }
  return acceleratorStatus;
}
